import type { Car } from './types';

export const initialCars: Car[] = [
  {
    id: '1',
    make: 'BMW',
    model: 'M440i xDrive',
    year: 2024,
    price: 75000,
    mileage: 1200,
    color: 'Alpine White',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engineSize: '3.0L',
    horsepower: 382,
    features: ['All-Wheel Drive', 'Adaptive Suspension', 'Panoramic Sunroof', 'Premium Sound System'],
    image: '/cars/bmw-m440i.png',
    images: ['/cars/bmw-m440i.png'],
    description: 'Experience ultimate performance with the BMW M440i. This luxury sedan combines power with precision.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    make: 'Mercedes-Benz',
    model: 'C63 AMG',
    year: 2023,
    price: 85000,
    mileage: 5600,
    color: 'Obsidian Black',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 505,
    features: ['Dynamic Performance Control', 'Adaptive Air Suspension', 'Burmester Sound System', 'LED Headlights'],
    image: '/cars/mercedes-c63.png',
    images: ['/cars/mercedes-c63.png'],
    description: 'Pure performance meets luxury. The Mercedes-Benz C63 AMG is engineered for those who demand excellence.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    make: 'Porsche',
    model: '911 Carrera S',
    year: 2024,
    price: 115000,
    mileage: 800,
    color: 'Racing Yellow',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engineSize: '3.0L Twin-Turbo',
    horsepower: 443,
    features: ['All-Wheel Drive', 'PASM Suspension', 'Bose Sound System', 'Adaptive Lighting'],
    image: '/cars/porsche-911.png',
    images: ['/cars/porsche-911.png'],
    description: 'An icon reimagined. The Porsche 911 Carrera S delivers timeless performance and thrilling acceleration.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    make: 'Audi',
    model: 'RS6 Avant',
    year: 2023,
    price: 105000,
    mileage: 12500,
    color: 'Daytona Gray',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 592,
    features: ['Quattro All-Wheel Drive', 'Ceramic Brakes', 'Bang & Olufsen Sound', 'Dynamic Ride Control'],
    image: '/cars/audi-rs6.png',
    images: ['/cars/audi-rs6.png'],
    description: 'Combine practicality with raw power. The Audi RS6 Avant is the ultimate performance wagon.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 95000,
    mileage: 3200,
    color: 'Solid Black',
    transmission: 'Automatic',
    fuelType: 'Electric',
    engineSize: 'Tri-Motor',
    horsepower: 1020,
    features: ['Autopilot', '17\" Touchscreen', 'Premium Sound', 'Supercharging'],
    image: '/cars/tesla-model-s.png',
    images: ['/cars/tesla-model-s.png'],
    description: 'The future of performance. Tesla Model S Plaid combines electric efficiency with supercar acceleration.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    make: 'Lamborghini',
    model: 'Urus',
    year: 2023,
    price: 225000,
    mileage: 2800,
    color: 'Titanium Gray',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 641,
    features: ['All-Terrain Drive Modes', 'Carbon Fiber Interior', 'Active Aerodynamics', 'Akrapovic Exhaust'],
    image: '/cars/lamborghini-urus.png',
    images: ['/cars/lamborghini-urus.png'],
    description: 'Luxury SUV redefined. The Lamborghini Urus combines supercar performance with SUV versatility.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
