import type { Car } from './types';

export const initialCars: Car[] = [
  {
    id: '1',
    make: 'BMW',
    model: 'M440i xDrive',
    year: 2024,
    price: 32000,
    currency: 'KWD',
    mileage: 1200,
    color: 'أبيض ألبيني',
    transmission: 'أوتوماتيك',
    fuelType: 'بنزين',
    engineSize: '3.0L',
    horsepower: 382,
    features: ['دفع رباعي', 'تعليق مكيف', 'سقف بانوراما', 'نظام صوتي فاخر'],
    image: '/cars/bmw-m440i.png',
    images: ['/cars/bmw-m440i.png'],
    description: 'اختبر الأداء النهائي مع BMW M440i. سيارة فاخرة تجمع بين القوة والدقة.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    make: 'Mercedes-Benz',
    model: 'C63 AMG',
    year: 2023,
    price: 36000,
    currency: 'KWD',
    mileage: 5600,
    color: 'أسود أوبسيديان',
    transmission: 'أوتوماتيك',
    fuelType: 'بنزين',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 505,
    features: ['التحكم الديناميكي بالأداء', 'تعليق هوائي مكيف', 'نظام صوتي Burmester', 'مصابيح LED'],
    image: '/cars/mercedes-c63.png',
    images: ['/cars/mercedes-c63.png'],
    description: 'الأداء النقي يلتقي بالفخامة. سيارة Mercedes-Benz C63 AMG مصممة للمتطلبين.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    make: 'Porsche',
    model: '911 Carrera S',
    year: 2024,
    price: 48000,
    currency: 'KWD',
    mileage: 800,
    color: 'أصفر سباق',
    transmission: 'أوتوماتيك',
    fuelType: 'بنزين',
    engineSize: '3.0L Twin-Turbo',
    horsepower: 443,
    features: ['دفع رباعي', 'تعليق PASM', 'نظام صوتي Bose', 'إضاءة تكيفية'],
    image: '/cars/porsche-911.png',
    images: ['/cars/porsche-911.png'],
    description: 'أيقونة جديدة. Porsche 911 Carrera S توفر أداء خالدة وتسارع مثير.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    make: 'Audi',
    model: 'RS6 Avant',
    year: 2023,
    price: 44000,
    currency: 'KWD',
    mileage: 12500,
    color: 'رمادي ديتونا',
    transmission: 'أوتوماتيك',
    fuelType: 'بنزين',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 592,
    features: ['دفع رباعي Quattro', 'فرامل سيراميك', 'نظام صوتي Bang & Olufsen', 'التحكم الديناميكي بالركوب'],
    image: '/cars/audi-rs6.png',
    images: ['/cars/audi-rs6.png'],
    description: 'ادمج العملية مع القوة الخام. Audi RS6 Avant هي سيارة الأداء العملية الأخيرة.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 40000,
    currency: 'KWD',
    mileage: 3200,
    color: 'أسود صلب',
    transmission: 'أوتوماتيك',
    fuelType: 'كهربائي',
    engineSize: 'محرك ثلاثي',
    horsepower: 1020,
    features: ['Autopilot', 'شاشة 17\"', 'نظام صوتي فاخر', 'Supercharging'],
    image: '/cars/tesla-model-s.png',
    images: ['/cars/tesla-model-s.png'],
    description: 'مستقبل الأداء. Tesla Model S Plaid يجمع بين الكفاءة الكهربائية وتسارع السيارة الخارقة.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    make: 'Lamborghini',
    model: 'Urus',
    year: 2023,
    price: 95000,
    currency: 'KWD',
    mileage: 2800,
    color: 'رمادي التيتانيوم',
    transmission: 'أوتوماتيك',
    fuelType: 'بنزين',
    engineSize: '4.0L Twin-Turbo',
    horsepower: 641,
    features: ['أوضاع القيادة بجميع التضاريس', 'داخلية ألياف الكربون', 'الديناميكا الهوائية النشطة', 'عادم Akrapovic'],
    image: '/cars/lamborghini-urus.png',
    images: ['/cars/lamborghini-urus.png'],
    description: 'إعادة تعريف سيارة الدفع الرباعي الفاخرة. Lamborghini Urus تجمع بين أداء السيارة الخارقة وتعددية الاستخدام.',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
